default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: users-service_development

test:
  <<: *default
  database: users-service_test

production:
  <<: *default
  database: users-service_production
  username: users-service
  password: <%= ENV['USERS-SERVICE_DATABASE_PASSWORD'] %>
